### PR TITLE
Exam submittal for data-scientist-intern-spring-2022

### PR DESCRIPTION
**Pull request by ner-aim**
Submission for Pradyumn Kumar Pottaptri for Bombora Data Scientist Intern

### CODE REVIEW

**Comment by NahsiN** [comment]
@ner-aim I don't see your answers in the .ipynb file. Are you sure you committed correctly?

**Comment by ner-aim** [comment]
> @ner-aim I don't see your answers in the .ipynb file. Are you sure you committed correctly?

I am pretty sure I did and it is in the submittals folder. I will check again and will let you know.

**Comment by NahsiN** [comment]
@ner-aim My bad, found it. Thanks! I clicked on the template by mistake.

**Comment by ner-aim** [comment]
> @ner-aim My bad, found it. Thanks! I clicked on the template by mistake.

That's alright! Thank you.

**Pull request closed without merging**
